# Generated by Django 4.2.2 on 2023-06-18 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=255)),
                ('lastName', models.CharField(default='', max_length=255)),
                ('userName', models.CharField(default='', max_length=255, unique=True)),
                ('organisation', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('active', models.BooleanField(default=0, max_length=255)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('modifiedBy', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
